<?php
$form = $this->form;
$fieldset = $form->get('student');

$name = $fieldset->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

$age = $fieldset->get('age');
$age->setAttribute('class', 'form-control');
$age->setAttribute('placeholder', 'Age');

$address = $fieldset->get('address');
$address->setAttribute('class', 'form-control');
$address->setAttribute('placeholder', 'address');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

<fieldset>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($age) ?>
    <?= $this->formElement($age) ?>
    <?= $this->formElementErrors()->render($age, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($address) ?>
    <?= $this->formElement($address) ?>
    <?= $this->formElementErrors()->render($address, ['class' => 'help-block']) ?>
</div>

</fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($fieldset->get('id'));
echo $this->form()->closeTag();